import * as XLSX from 'xlsx';

export interface ParsedStudentRow {
  rowIndex: number;
  firstName: string;
  name: string;
  loginUsername: string;
  rollNumber: string;
  phone: string;
  email?: string;
  password: string;
  isPasswordAutoGenerated: boolean;
  batches: string[];
  batchModes: Record<string, string[]>;
  batch: string;
  course?: string;
  type: string;
  totalFees: number;
  feesPaid: number;
  dueFees: number;
  courseDuration: string;
  joiningDate: string;
  modeOfPayment: 'cash' | 'gpay' | 'others';
  transactionId?: string;
  isValid: boolean;
  validationErrors: string[];
}

export interface ParsedStudentUploadResult {
  students: ParsedStudentRow[];
  stats: {
    totalRows: number;
    validCount: number;
    invalidCount: number;
    totalFeesSum: number;
    totalPaidSum: number;
  };
  headersFound: Record<string, string>;
  fileName: string;
}

/**
 * Normalizes an Excel date serial or string into YYYY-MM-DD
 */
function normalizeDate(val: any): string {
  if (!val) return new Date().toISOString().split('T')[0];
  
  if (typeof val === 'number') {
    // Excel date serial conversion
    const date = new Date(Math.round((val - 25569) * 86400 * 1000));
    if (!isNaN(date.getTime())) {
      return date.toISOString().split('T')[0];
    }
  }

  const str = String(val).trim();
  // Handle DD/MM/YYYY or DD-MM-YYYY
  const dmyMatch = str.match(/^(\d{1,2})[\/\-](\d{1,2})[\/\-](\d{4})$/);
  if (dmyMatch) {
    const day = dmyMatch[1].padStart(2, '0');
    const month = dmyMatch[2].padStart(2, '0');
    const year = dmyMatch[3];
    return `${year}-${month}-${day}`;
  }

  // Handle YYYY-MM-DD
  const ymdMatch = str.match(/^(\d{4})[\/\-](\d{1,2})[\/\-](\d{1,2})$/);
  if (ymdMatch) {
    const year = ymdMatch[1];
    const month = ymdMatch[2].padStart(2, '0');
    const day = ymdMatch[3].padStart(2, '0');
    return `${year}-${month}-${day}`;
  }

  return str;
}

/**
 * Normalizes Course Duration (3, 6, 9, 12, 18, 24 months)
 */
function normalizeDuration(val: any): string {
  if (!val) return '12 Months';
  const str = String(val).trim().toLowerCase();
  const numMatch = str.match(/\d+/);
  if (numMatch) {
    const num = parseInt(numMatch[0], 10);
    if ([3, 6, 9, 12, 18, 24].includes(num)) {
      return `${num} Months`;
    }
  }
  return '12 Months';
}

/**
 * Normalizes Payment Mode (cash, gpay, others)
 */
function normalizePaymentMode(val: any): 'cash' | 'gpay' | 'others' {
  if (!val) return 'cash';
  const str = String(val).trim().toLowerCase();
  if (str.includes('gpay') || str.includes('google') || str.includes('upi') || str.includes('phonepe') || str.includes('paytm')) {
    return 'gpay';
  }
  if (str.includes('cash')) {
    return 'cash';
  }
  return 'others';
}

/**
 * Cleans phone number to numeric digits
 */
function cleanPhone(val: any): string {
  if (!val) return '';
  const digits = String(val).replace(/\D/g, '');
  if (digits.length > 10 && digits.startsWith('91')) {
    return digits.slice(2, 12);
  }
  return digits.slice(-10);
}

/**
 * Parses an Excel Workbook for Bulk Student Registration
 * Column headers can appear in ANY order.
 */
export async function parseStudentUploadFile(file: File, availableBatches: Array<{ id: string; batchName: string; course?: string }>): Promise<ParsedStudentUploadResult> {
  const buffer = await file.arrayBuffer();
  const workbook = XLSX.read(buffer, { type: 'array' });

  // Use the first sheet or find sheet with student data
  const sheetName = workbook.SheetNames[0];
  const sheet = workbook.Sheets[sheetName];
  const rawRows: any[][] = XLSX.utils.sheet_to_json(sheet, { header: 1 });

  if (!rawRows || rawRows.length < 2) {
    throw new Error('The uploaded Excel file does not contain enough rows.');
  }

  // Find header row in first 10 rows
  let headerRowIndex = -1;
  let nameCol = -1;
  let usernameCol = -1;
  let batchCol = -1;
  let modeCol = -1;
  let totalFeeCol = -1;
  let paidFeeCol = -1;
  let durationCol = -1;
  let joiningDateCol = -1;
  let phoneCol = -1;
  let emailCol = -1;
  let paymentModeCol = -1;
  let txnIdCol = -1;
  let passwordCol = -1;

  const headersFound: Record<string, string> = {};

  for (let i = 0; i < Math.min(rawRows.length, 10); i++) {
    const row = rawRows[i];
    if (!Array.isArray(row)) continue;

    let matchedCount = 0;
    row.forEach((cell, idx) => {
      if (typeof cell !== 'string') return;
      const h = cell.toLowerCase().trim().replace(/[\r\n\t_]+/g, ' ');

      // 1. Username / Roll Number (Check first to avoid 'username' triggering 'name')
      if (/^(user\s*name|roll\s*(no|number)?|reg\s*(no|number)?|admission\s*(no|number)?)$/i.test(h) || h.includes('roll') || h.includes('username') || h.includes('user name') || h.includes('reg no') || h.includes('admission no')) {
        usernameCol = idx;
        headersFound['Username'] = cell;
        matchedCount++;
      }
      // 2. Student Full Name (Exclude user/father/mother/batch names)
      else if (/^(student\s*)?(full\s*)?name(\s*of\s*student)?$/i.test(h) || (h.includes('name') && !h.includes('user') && !h.includes('father') && !h.includes('mother') && !h.includes('batch'))) {
        nameCol = idx;
        headersFound['Name'] = cell;
        matchedCount++;
      } else if (/^batch(es)?(\s*name)?$/i.test(h) || (h.includes('batch') && !h.includes('mode'))) {
        batchCol = idx;
        headersFound['Batch'] = cell;
        matchedCount++;
      } else if (/^(class\s*)?mode$/i.test(h) || h.includes('mode of class')) {
        modeCol = idx;
        headersFound['Class Mode'] = cell;
      } else if (/^(total\s*)?(course\s*)?fees?(\s*amount)?$/i.test(h) || (h.includes('total') && h.includes('fee'))) {
        totalFeeCol = idx;
        headersFound['Total Fees'] = cell;
        matchedCount++;
      } else if (/^(fees?\s*)?paid(\s*amount)?|paid\s*(fees?|amount)?$/i.test(h) || (h.includes('paid') && h.includes('fee'))) {
        paidFeeCol = idx;
        headersFound['Paid Fees'] = cell;
        matchedCount++;
      } else if (/^(course\s*)?duration|validity|months$/i.test(h) || h.includes('duration')) {
        durationCol = idx;
        headersFound['Course Duration'] = cell;
      } else if (/^(joining\s*date|date\s*of\s*joining|doj|admission\s*date)$/i.test(h) || h.includes('joining')) {
        joiningDateCol = idx;
        headersFound['Joining Date'] = cell;
      } else if (/^phone(\s*number)?|mobile(\s*number)?|contact(\s*number)?$/i.test(h) || h.includes('phone') || h.includes('mobile')) {
        phoneCol = idx;
        headersFound['Phone'] = cell;
        matchedCount++;
      } else if (/^email(\s*id)?$/i.test(h) || h.includes('email')) {
        emailCol = idx;
        headersFound['Email'] = cell;
      } else if (/^(mode\s*of\s*)?payment(\s*mode|\s*method)?$/i.test(h) || (h.includes('payment') && h.includes('mode'))) {
        paymentModeCol = idx;
        headersFound['Mode of Payment'] = cell;
      } else if (/^transaction\s*(id|number)?|txn\s*(id)?|utr|ref(\s*no)?$/i.test(h) || h.includes('transaction') || h.includes('utr')) {
        txnIdCol = idx;
        headersFound['Transaction ID'] = cell;
      } else if (/^password|pass|login\s*password$/i.test(h) || h.includes('password')) {
        passwordCol = idx;
        headersFound['Password'] = cell;
      }
    });

    // If at least 2 primary columns matched, this is our header row
    if (matchedCount >= 2) {
      headerRowIndex = i;
      break;
    }
  }

  if (headerRowIndex === -1) {
    throw new Error('Could not automatically identify the header row. Please make sure the Excel file has column headers like Name, Username, Phone, Batch, Total Fee, etc.');
  }

  const students: ParsedStudentRow[] = [];
  const seenUsernames = new Set<string>();

  for (let r = headerRowIndex + 1; r < rawRows.length; r++) {
    const row = rawRows[r];
    if (!row || row.length === 0 || !row.some(cell => cell !== undefined && cell !== null && String(cell).trim())) {
      continue; // Skip empty rows
    }

    const rawName = nameCol !== -1 ? String(row[nameCol] || '').trim() : '';
    const rawUsername = usernameCol !== -1 ? String(row[usernameCol] || '').trim() : '';
    const rawPhone = phoneCol !== -1 ? cleanPhone(row[phoneCol]) : '';
    const rawEmail = emailCol !== -1 ? String(row[emailCol] || '').trim() : '';
    const rawBatch = batchCol !== -1 ? String(row[batchCol] || '').trim() : '';
    const rawMode = modeCol !== -1 ? String(row[modeCol] || '').trim().toLowerCase() : 'offline';
    const rawTotalFee = totalFeeCol !== -1 ? Number(row[totalFeeCol]) || 0 : 0;
    const rawPaidFee = paidFeeCol !== -1 ? Number(row[paidFeeCol]) || 0 : 0;
    const rawDuration = durationCol !== -1 ? normalizeDuration(row[durationCol]) : '12 Months';
    const rawJoiningDate = joiningDateCol !== -1 ? normalizeDate(row[joiningDateCol]) : new Date().toISOString().split('T')[0];
    const rawPaymentMode = paymentModeCol !== -1 ? normalizePaymentMode(row[paymentModeCol]) : 'cash';
    const rawTxnId = txnIdCol !== -1 ? String(row[txnIdCol] || '').trim() : '';
    const rawPassword = passwordCol !== -1 ? String(row[passwordCol] || '').trim() : '';

    const validationErrors: string[] = [];

    if (!rawName) validationErrors.push('Student Name is missing');
    if (!rawUsername) validationErrors.push('Username / Roll Number is missing');
    if (!rawPhone || rawPhone.length < 10) validationErrors.push('Valid 10-digit Phone Number is required');
    if (rawPaidFee > rawTotalFee) validationErrors.push(`Paid fees (₹${rawPaidFee}) cannot exceed Total fees (₹${rawTotalFee})`);

    // Duplicate check in Excel
    const lowerUsername = rawUsername.toLowerCase();
    if (lowerUsername) {
      if (seenUsernames.has(lowerUsername)) {
        validationErrors.push(`Duplicate Roll Number in sheet: ${rawUsername}`);
      } else {
        seenUsernames.add(lowerUsername);
      }
    }

    // Password generation: if password given, use it. Otherwise Username + Last 4 digits of Phone
    let finalPassword = rawPassword;
    let isAutoPassword = false;
    if (!finalPassword && rawUsername) {
      const last4 = rawPhone.length >= 4 ? rawPhone.slice(-4) : (rawPhone || '1234');
      finalPassword = rawUsername + last4;
      isAutoPassword = true;
    }

    // Smart Batch Matching (supports '43', 'LDC 43', 'Batch 44', '44', 'UDC 45', '100', 'UDC 100', etc.)
    let resolvedBatchName = rawBatch;
    let resolvedCourse = '';
    
    const cleanRawBatch = rawBatch.trim().toLowerCase();
    const digitsRaw = cleanRawBatch.replace(/\D/g, '');
    
    // 1. Direct name or id match
    let matchedBatch = availableBatches.find(
      b => b.batchName.toLowerCase() === cleanRawBatch || b.id.toLowerCase() === cleanRawBatch
    );
    
    // 2. Full Course + BatchName match (e.g. "LDC 43", "UDC 45", "LDC Batch 44", "UDC 100")
    if (!matchedBatch) {
      matchedBatch = availableBatches.find(b => {
        const combined = `${b.course || ''} ${b.batchName}`.toLowerCase().replace(/[^a-z0-9]/g, '');
        const cleanRawAlphaNum = cleanRawBatch.replace(/[^a-z0-9]/g, '');
        return combined === cleanRawAlphaNum;
      });
    }

    // 3. Match numeric batch identifier (e.g. raw "43" or "LDC 43" vs batch "43" / "Batch 43")
    if (!matchedBatch && digitsRaw) {
      const numericMatches = availableBatches.filter(b => {
        const bDigits = b.batchName.replace(/\D/g, '');
        return bDigits === digitsRaw;
      });
      if (numericMatches.length === 1) {
        matchedBatch = numericMatches[0];
      } else if (numericMatches.length > 1) {
        // Disambiguate by course name if present in raw string
        const courseMatch = numericMatches.find(b => 
          b.course && cleanRawBatch.includes(b.course.toLowerCase())
        );
        matchedBatch = courseMatch || numericMatches[0];
      }
    }

    // 4. Fallback substring match
    if (!matchedBatch) {
      matchedBatch = availableBatches.find(b => {
        const bName = b.batchName.toLowerCase();
        return cleanRawBatch.includes(bName) || bName.includes(cleanRawBatch);
      });
    }

    if (matchedBatch) {
      resolvedBatchName = matchedBatch.batchName;
      resolvedCourse = matchedBatch.course || '';
    } else if (availableBatches.length > 0 && !resolvedBatchName) {
      resolvedBatchName = availableBatches[0].batchName;
      resolvedCourse = availableBatches[0].course || '';
    }

    const classMode = ['online', 'offline', 'recorded'].includes(rawMode) ? rawMode : 'offline';
    const batchesList = resolvedBatchName ? [resolvedBatchName] : [];
    const batchModesMap: Record<string, string[]> = resolvedBatchName ? { [resolvedBatchName]: [classMode] } : {};

    const dueFees = Math.max(0, rawTotalFee - rawPaidFee);

    students.push({
      rowIndex: r + 1,
      firstName: rawName,
      name: rawName,
      loginUsername: rawUsername,
      rollNumber: rawUsername,
      phone: rawPhone,
      email: rawEmail,
      password: finalPassword,
      isPasswordAutoGenerated: isAutoPassword,
      batches: batchesList,
      batchModes: batchModesMap,
      batch: resolvedBatchName,
      course: resolvedCourse,
      type: classMode,
      totalFees: rawTotalFee,
      feesPaid: rawPaidFee,
      dueFees,
      courseDuration: rawDuration,
      joiningDate: rawJoiningDate,
      modeOfPayment: rawPaymentMode,
      transactionId: rawTxnId,
      isValid: validationErrors.length === 0,
      validationErrors
    });
  }

  const validCount = students.filter(s => s.isValid).length;
  const invalidCount = students.length - validCount;
  const totalFeesSum = students.reduce((acc, s) => acc + s.totalFees, 0);
  const totalPaidSum = students.reduce((acc, s) => acc + s.feesPaid, 0);

  return {
    students,
    stats: {
      totalRows: students.length,
      validCount,
      invalidCount,
      totalFeesSum,
      totalPaidSum
    },
    headersFound,
    fileName: file.name
  };
}
