import { Permissions, Permission } from './permissions';

export const RolePermissions: Record<string, Permission[]> = {
  // Super Admin has all permissions globally
  super_admin: Object.values(Permissions),

  // Admins can do almost everything within their tenant
  admin: [
    Permissions.COURSE_READ,
    Permissions.COURSE_CREATE,
    Permissions.COURSE_UPDATE,
    Permissions.COURSE_DELETE,
    Permissions.VIDEO_READ,
    Permissions.VIDEO_UPLOAD,
    Permissions.VIDEO_UPDATE,
    Permissions.VIDEO_DELETE,
    Permissions.RESOURCE_READ,
    Permissions.RESOURCE_CREATE,
    Permissions.RESOURCE_UPDATE,
    Permissions.RESOURCE_DELETE,
    Permissions.STUDENT_READ,
    Permissions.STUDENT_CREATE,
    Permissions.STUDENT_UPDATE,
    Permissions.STUDENT_DELETE,
    Permissions.STUDENT_ENROLL,
    Permissions.STAFF_READ,
    Permissions.STAFF_CREATE,
    Permissions.STAFF_UPDATE,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_MARK,
    Permissions.ATTENDANCE_START,
    Permissions.ATTENDANCE_END,
    Permissions.LIVE_CLASS_READ,
    Permissions.LIVE_CLASS_CREATE,
    Permissions.LIVE_CLASS_UPDATE,
    Permissions.LIVE_CLASS_DELETE,
    Permissions.LIVE_CLASS_START,
    Permissions.LIVE_CLASS_END,
    Permissions.LIVE_CLASS_MODERATE,
    Permissions.EXAM_READ,
    Permissions.EXAM_CREATE,
    Permissions.EXAM_UPDATE,
    Permissions.EXAM_DELETE,
    Permissions.EXAM_PUBLISH,
    Permissions.EXAM_EVALUATE,
    Permissions.EXAM_REVIEW,
    Permissions.QUESTION_BANK_READ,
    Permissions.QUESTION_BANK_MANAGE,
    Permissions.FEES_READ,
    Permissions.FEES_CREATE,
    Permissions.FEES_UPDATE,
    Permissions.FEES_DELETE,
    Permissions.MARKS_READ,
    Permissions.MARKS_CREATE,
    Permissions.MARKS_UPDATE,
    Permissions.CHATBOT_ASK,
    Permissions.CHATBOT_HISTORY_READ,
    Permissions.METRICS_READ,
    Permissions.ANALYTICS_READ,
    Permissions.FILE_UPLOAD,
    Permissions.FILE_DELETE,
    Permissions.CRM_READ,
    Permissions.CRM_MANAGE,
    Permissions.LEAD_READ,
    Permissions.LEAD_MANAGE,
    Permissions.ADMISSION_READ,
    Permissions.ADMISSION_MANAGE,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.ANNOUNCEMENT_CREATE,
    Permissions.SESSION_REVOKE_SELF,
    Permissions.SESSION_REVOKE_ALL,
    Permissions.AUDIT_READ,
  ],

  // Staff: manages academic content and students, no financial admin
  staff: [
    Permissions.COURSE_READ,
    Permissions.COURSE_CREATE,
    Permissions.COURSE_UPDATE,
    Permissions.VIDEO_READ,
    Permissions.VIDEO_UPLOAD,
    Permissions.VIDEO_UPDATE,
    Permissions.RESOURCE_READ,
    Permissions.RESOURCE_CREATE,
    Permissions.RESOURCE_UPDATE,
    Permissions.STUDENT_READ,
    Permissions.STUDENT_ENROLL,
    Permissions.STAFF_READ,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_MARK,
    Permissions.ATTENDANCE_START,
    Permissions.ATTENDANCE_END,
    Permissions.LIVE_CLASS_READ,
    Permissions.LIVE_CLASS_CREATE,
    Permissions.LIVE_CLASS_UPDATE,
    Permissions.LIVE_CLASS_START,
    Permissions.LIVE_CLASS_END,
    Permissions.LIVE_CLASS_MODERATE,
    Permissions.EXAM_READ,
    Permissions.EXAM_CREATE,
    Permissions.EXAM_UPDATE,
    Permissions.EXAM_PUBLISH,
    Permissions.EXAM_EVALUATE,
    Permissions.EXAM_REVIEW,
    Permissions.QUESTION_BANK_READ,
    Permissions.QUESTION_BANK_MANAGE,
    Permissions.MARKS_READ,
    Permissions.MARKS_CREATE,
    Permissions.MARKS_UPDATE,
    Permissions.CHATBOT_ASK,
    Permissions.METRICS_READ,
    Permissions.FILE_UPLOAD,
    Permissions.ANNOUNCEMENT_READ,
    Permissions.ANNOUNCEMENT_CREATE,
    Permissions.SESSION_REVOKE_SELF,
    Permissions.FEES_READ,
  ],

  // Teachers: content and live class management (subset of staff)
  teacher: [
    Permissions.COURSE_READ,
    Permissions.COURSE_CREATE,
    Permissions.COURSE_UPDATE,
    Permissions.VIDEO_READ,
    Permissions.VIDEO_UPLOAD,
    Permissions.VIDEO_UPDATE,
    Permissions.RESOURCE_READ,
    Permissions.RESOURCE_CREATE,
    Permissions.RESOURCE_UPDATE,
    Permissions.STUDENT_READ,
    Permissions.ATTENDANCE_READ,
    Permissions.ATTENDANCE_MARK,
    Permissions.ATTENDANCE_START,
    Permissions.ATTENDANCE_END,
    Permissions.LIVE_CLASS_READ,
    Permissions.LIVE_CLASS_CREATE,
    Permissions.LIVE_CLASS_UPDATE,
    Permissions.LIVE_CLASS_START,
    Permissions.LIVE_CLASS_END,
    Permissions.LIVE_CLASS_MODERATE,
    Permissions.EXAM_READ,
    Permissions.EXAM_CREATE,
    Permissions.EXAM_UPDATE,
    Permissions.EXAM_EVALUATE,
    Permissions.QUESTION_BANK_READ,
    Permissions.QUESTION_BANK_MANAGE,
    Permissions.MARKS_READ,
    Permissions.CHATBOT_ASK,
    Permissions.FILE_UPLOAD,
    Permissions.SESSION_REVOKE_SELF,
  ],

  // Students: limited read + self-service only
  student: [
    Permissions.COURSE_READ,
    Permissions.VIDEO_READ,
    Permissions.RESOURCE_READ,
    Permissions.LIVE_CLASS_READ,
    Permissions.CHATBOT_ASK,
    Permissions.EXAM_TAKE,
    Permissions.EXAM_REVIEW,       // Can review their own completed exams
    Permissions.ATTENDANCE_READ,   // Can view their own attendance
    Permissions.MARKS_READ,        // Can view their own marks
    Permissions.ANNOUNCEMENT_READ,
    Permissions.SESSION_REVOKE_SELF,
  ],
};
